# Generated by Django 5.2.7 on 2025-10-25 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('external_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='accounts.paymentaccounts')),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_lines', to='payment.payment')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_lines', to='accounts.transaction')),
            ],
            options={
                'db_table': 'finance_bank_statement_lines',
                'ordering': ['-statement_date'],
                'indexes': [models.Index(fields=['account', 'statement_date'], name='idx_stmt_acc_date')],
            },
        ),
    ]
