# Generated by Django 5.2.7 on 2025-10-25 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='pickup_station',
            field=models.ForeignKey(blank=True, help_text='Selected pickup station if delivery_type is pickup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_addresses', to='business.pickupstations'),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addressvalidation',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='addresses.addressbook'),
        ),
        migrations.AddField(
            model_name='addressvalidation',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deliveryregion',
            index=models.Index(fields=['name'], name='idx_delivery_region_name'),
        ),
        migrations.AddIndex(
            model_name='deliveryregion',
            index=models.Index(fields=['county'], name='idx_delivery_region_county'),
        ),
        migrations.AddIndex(
            model_name='deliveryregion',
            index=models.Index(fields=['is_active'], name='idx_delivery_region_active'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryregion',
            unique_together={('name', 'county')},
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['user'], name='idx_address_user'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['address_type'], name='idx_address_type'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['delivery_type'], name='idx_address_delivery_type'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['county'], name='idx_address_county'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['constituency'], name='idx_address_constituency'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['is_default_shipping'], name='idx_address_default_shipping'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['is_default_billing'], name='idx_address_default_billing'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['is_verified'], name='idx_address_verified'),
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['created_at'], name='idx_address_created_at'),
        ),
        migrations.AddIndex(
            model_name='addressvalidation',
            index=models.Index(fields=['address'], name='idx_address_validation_address'),
        ),
        migrations.AddIndex(
            model_name='addressvalidation',
            index=models.Index(fields=['status'], name='idx_address_validation_status'),
        ),
        migrations.AddIndex(
            model_name='addressvalidation',
            index=models.Index(fields=['is_valid'], name='idx_address_validation_valid'),
        ),
        migrations.AddIndex(
            model_name='addressvalidation',
            index=models.Index(fields=['validated_at'], name='idx_addr_validated_at'),
        ),
    ]
