# Generated by Django 5.2.7 on 2025-10-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliveryregion',
            unique_together={('name', 'county')},
        ),
    ]
