# Generated by Django 5.2.7 on 2025-10-25 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 2, 32, 11, 153103)),
        ),
    ]
