# Generated by Django 5.2.8 on 2025-12-11 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 12, 1, 6, 9, 493665)),
        ),
    ]
