# Generated by Django 5.2.8 on 2025-12-15 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 15, 23, 51, 13, 194045)),
        ),
    ]
