# Generated by Django 5.2.8 on 2025-12-15 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 0, 57, 51, 804173)),
        ),
    ]
