# Generated by Django 5.2.7 on 2025-11-15 11:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase'), ('Expense', 'Expense')], max_length=50, verbose_name='Transaction Type')),
                ('ref_no', models.CharField(max_length=100, verbose_name='Transaction ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount')),
                ('payment_note', models.TextField(blank=True, null=True, verbose_name='Payment Note')),
                ('payment_document', models.FileField(blank=True, null=True, upload_to='payments/attachments', verbose_name='Attachment')),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Payment Date')),
            ],
            options={
                'verbose_name': 'Transaction Payment',
                'verbose_name_plural': 'Transaction Payments',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=20, unique=True)),
                ('voucher_type', models.CharField(choices=[('Payment', 'Payment'), ('Journal', 'Journal'), ('Adjustment', 'Adjustment')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('voucher_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-voucher_date'],
            },
        ),
        migrations.CreateModel(
            name='VoucherAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], max_length=50)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('both', 'Both')], default='both', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Voucher Item',
                'verbose_name_plural': 'Voucher Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Account Types',
                'verbose_name_plural': 'Account Types',
                'db_table': 'account_types',
                'indexes': [models.Index(fields=['name'], name='idx_account_types_name')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=16)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentaccounts', to='accounts.accounttypes')),
            ],
            options={
                'verbose_name': 'Payment Accounts',
                'verbose_name_plural': 'Payment Accounts',
                'db_table': 'payment_accounts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=50)),
                ('description', models.TextField()),
                ('reference_type', models.CharField(help_text='Type of document this transaction relates to (invoice, expense, etc.)', max_length=100)),
                ('reference_id', models.CharField(help_text='ID of the referenced document', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.paymentaccounts')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
