# Generated by Django 5.2.7 on 2025-10-25 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionpayment',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_by_payments', to=settings.AUTH_USER_MODEL, verbose_name='Paid By'),
        ),
        migrations.AddField(
            model_name='transactionpayment',
            name='paid_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_to_payments', to=settings.AUTH_USER_MODEL, verbose_name='Paid To'),
        ),
    ]
