# Generated by Django 5.2 on 2025-09-11 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_payments', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='transactionpayment',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_payments', to='accounts.paymentaccounts'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='voucheraudit',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucheraudit',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='accounts.voucher'),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_voucher_items', to='accounts.paymentaccounts'),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_voucher_items', to='accounts.paymentaccounts'),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.voucher'),
        ),
        migrations.AddIndex(
            model_name='paymentaccounts',
            index=models.Index(fields=['name'], name='idx_payment_accounts_name'),
        ),
        migrations.AddIndex(
            model_name='paymentaccounts',
            index=models.Index(fields=['account_number'], name='idx_payment_accounts_number'),
        ),
        migrations.AddIndex(
            model_name='paymentaccounts',
            index=models.Index(fields=['account_type'], name='idx_payment_accounts_type'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='idx_transaction_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='idx_transaction_type'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='idx_transaction_reference'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account'], name='idx_transaction_account'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_by'], name='idx_transaction_created_by'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='idx_transaction_created_at'),
        ),
        migrations.AddIndex(
            model_name='transactionpayment',
            index=models.Index(fields=['transaction_type'], name='idx_transaction_payment_type'),
        ),
        migrations.AddIndex(
            model_name='transactionpayment',
            index=models.Index(fields=['ref_no'], name='idx_transaction_payment_ref_no'),
        ),
        migrations.AddIndex(
            model_name='transactionpayment',
            index=models.Index(fields=['payment'], name='idx_txn_pay_payment'),
        ),
        migrations.AddIndex(
            model_name='transactionpayment',
            index=models.Index(fields=['payment_account'], name='idx_txn_pay_account'),
        ),
        migrations.AddIndex(
            model_name='transactionpayment',
            index=models.Index(fields=['paid_by'], name='idx_txn_paid_by'),
        ),
        migrations.AddIndex(
            model_name='transactionpayment',
            index=models.Index(fields=['paid_to'], name='idx_txn_paid_to'),
        ),
        migrations.AddIndex(
            model_name='transactionpayment',
            index=models.Index(fields=['payment_date'], name='idx_txn_pay_date'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['reference_number'], name='idx_voucher_reference'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_type'], name='idx_voucher_type'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_date'], name='idx_voucher_date'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['status'], name='idx_voucher_status'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_voucher_content'),
        ),
        migrations.AddIndex(
            model_name='voucheraudit',
            index=models.Index(fields=['voucher'], name='idx_voucher_audit_voucher'),
        ),
        migrations.AddIndex(
            model_name='voucheraudit',
            index=models.Index(fields=['action'], name='idx_voucher_audit_action'),
        ),
        migrations.AddIndex(
            model_name='voucheraudit',
            index=models.Index(fields=['action_by'], name='idx_voucher_audit_action_by'),
        ),
        migrations.AddIndex(
            model_name='voucheraudit',
            index=models.Index(fields=['action_date'], name='idx_voucher_audit_action_date'),
        ),
        migrations.AddIndex(
            model_name='voucheritem',
            index=models.Index(fields=['voucher'], name='idx_voucher_item_voucher'),
        ),
        migrations.AddIndex(
            model_name='voucheritem',
            index=models.Index(fields=['debit_account'], name='idx_vitem_debit_acct'),
        ),
        migrations.AddIndex(
            model_name='voucheritem',
            index=models.Index(fields=['credit_account'], name='idx_vitem_credit_acct'),
        ),
        migrations.AddIndex(
            model_name='voucheritem',
            index=models.Index(fields=['account_type'], name='idx_vitem_acct_type'),
        ),
    ]
