# Generated by Django 5.2.8 on 2025-12-15 21:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccounts',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccounts',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccounts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccounts',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenya Shilling (KES)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)')], default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='paymentaccounts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccounts',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccounts',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentaccounts',
            name='swift_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccounts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentaccounts',
            name='account_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentaccounts',
            name='account_type',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('cash', 'Cash Account'), ('credit_card', 'Credit Card'), ('investment', 'Investment Account'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], default='bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentaccounts',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddIndex(
            model_name='paymentaccounts',
            index=models.Index(fields=['status'], name='idx_payment_accounts_status'),
        ),
        migrations.AddIndex(
            model_name='paymentaccounts',
            index=models.Index(fields=['currency'], name='idx_payment_accounts_currency'),
        ),
    ]
