# Generated by Django 5.2.8 on 2025-12-11 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_business_products_default_price_and_more'),
        ('purchases', '0001_initial'),
        ('stockinventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='product.products'),
        ),
        migrations.AlterField(
            model_name='purchaseitems',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseitems', to='stockinventory.stockinventory', verbose_name='Purchasse Item'),
        ),
    ]
