# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        ('stockinventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitems',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseitems', to='stockinventory.stockinventory', verbose_name='Purchasse Item'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='original_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='purchases.purchase'),
        ),
        migrations.AddField(
            model_name='purchasereturneditem',
            name='return_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_items', to='purchases.purchasereturn'),
        ),
        migrations.AddField(
            model_name='purchasereturneditem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_items', to='stockinventory.stockinventory'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['branch'], name='idx_purchase_branch'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier'], name='idx_purchase_supplier'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['added_by'], name='idx_purchase_added_by'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_id'], name='idx_purchase_purchase_id'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['date_added'], name='idx_purchase_date_added'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['date_updated'], name='idx_purchase_date_updated'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_status'], name='idx_purchase_purchase_status'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['payment_status'], name='idx_purchase_payment_status'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['paymethod'], name='idx_purchase_paymethod'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['delete_status'], name='idx_purchase_delete_status'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_order'], name='idx_purchase_purchase_order'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['workflow_status'], name='idx_purchase_workflow_status'),
        ),
        migrations.AddIndex(
            model_name='purchaseitems',
            index=models.Index(fields=['purchase'], name='idx_purchase_items_purchase'),
        ),
        migrations.AddIndex(
            model_name='purchaseitems',
            index=models.Index(fields=['stock_item'], name='idx_purchase_items_stock_item'),
        ),
        migrations.AddIndex(
            model_name='purchaseitems',
            index=models.Index(fields=['date_added'], name='idx_purchase_items_date_added'),
        ),
        migrations.AddIndex(
            model_name='purchaseitems',
            index=models.Index(fields=['date_updated'], name='idx_purchase_items_updated'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['added_by'], name='idx_purchase_return_added_by'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['return_id'], name='idx_purchase_return_return_id'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['original_purchase'], name='idx_purchase_return_original'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['date_returned'], name='idx_purchase_return_returned'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['payment_status'], name='idx_purchase_return_pay_status'),
        ),
        migrations.AddIndex(
            model_name='purchasereturneditem',
            index=models.Index(fields=['return_record'], name='idx_purchase_returned_record'),
        ),
        migrations.AddIndex(
            model_name='purchasereturneditem',
            index=models.Index(fields=['stock_item'], name='idx_purchase_returned_stock'),
        ),
    ]
