# Generated by Django 5.2.7 on 2025-11-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_orders.baseorder')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('inventory_reserved', models.BooleanField(default=False, help_text='Whether inventory has been reserved for this order')),
                ('inventory_allocated', models.BooleanField(default=False, help_text='Whether inventory has been allocated for this order')),
                ('inventory_reservation_expires', models.DateTimeField(blank=True, help_text='When the inventory reservation expires', null=True)),
                ('backorder_items', models.JSONField(blank=True, help_text='Items that are backordered', null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'E-commerce Order',
                'verbose_name_plural': 'E-commerce Orders',
                'db_table': 'ecommerce_orders',
            },
            bases=('core_orders.baseorder',),
        ),
    ]
