# Generated by Django 5.2.7 on 2025-10-25 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_settings', models.JSONField(blank=True, default=dict, help_text='Theme configuration (preset, colors, menu mode, etc.)')),
                ('notification_settings', models.JSONField(blank=True, default=dict, help_text='Notification preferences')),
                ('dashboard_layout', models.JSONField(blank=True, default=dict, help_text='Dashboard widget layout')),
                ('language', models.CharField(default='en', help_text='User interface language', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'indexes': [models.Index(fields=['user'], name='idx_user_preferences_user')],
            },
        ),
    ]
