# Generated by Django 5.2.7 on 2025-11-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='enforce_password_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='require_password_change_on_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
