# Generated by Django 5.2.7 on 2025-10-25 21:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('defect_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('average_lead_time_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('total_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='contacts.contact')),
            ],
            options={
                'db_table': 'proc_supplier_performance',
                'indexes': [models.Index(fields=['supplier'], name='idx_sup_perf_supplier'), models.Index(fields=['period_start'], name='idx_sup_perf_start'), models.Index(fields=['period_end'], name='idx_sup_perf_end'), models.Index(fields=['on_time_delivery_rate'], name='idx_sup_perf_delivery_rate'), models.Index(fields=['defect_rate'], name='idx_sup_perf_defect_rate'), models.Index(fields=['average_lead_time_days'], name='idx_sup_perf_lead_time'), models.Index(fields=['total_spend'], name='idx_sup_perf_total_spend'), models.Index(fields=['created_at'], name='idx_sup_perf_created'), models.Index(fields=['supplier', 'period_start', 'period_end'], name='idx_sup_perf_period')],
            },
        ),
    ]
