# Generated by Django 5.2.7 on 2025-11-15 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('core_orders', '0001_initial'),
        ('stockinventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsession',
            name='converted_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_cart', to='core_orders.baseorder'),
        ),
        migrations.AddField(
            model_name='cartsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cartsession'),
        ),
        migrations.AddField(
            model_name='cartcoupon',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='cart.cartsession'),
        ),
        migrations.AddField(
            model_name='cartcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_coupons', to='cart.coupon'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='cart.coupon'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedforlater',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='stockinventory.stockinventory'),
        ),
        migrations.AddField(
            model_name='savedforlater',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cartsession',
            index=models.Index(fields=['session_key'], name='idx_cart_session_key'),
        ),
        migrations.AddIndex(
            model_name='cartsession',
            index=models.Index(fields=['user'], name='idx_cart_session_user'),
        ),
        migrations.AddIndex(
            model_name='cartsession',
            index=models.Index(fields=['is_active'], name='idx_cart_session_active'),
        ),
        migrations.AddIndex(
            model_name='cartsession',
            index=models.Index(fields=['created_at'], name='idx_cart_session_created_at'),
        ),
        migrations.AddIndex(
            model_name='cartsession',
            index=models.Index(fields=['expires_at'], name='idx_cart_session_expires_at'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='idx_cart_item_cart'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['stock_item'], name='idx_cart_item_stock'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['added_at'], name='idx_cart_item_added_at'),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'user')},
        ),
        migrations.AddIndex(
            model_name='savedforlater',
            index=models.Index(fields=['user'], name='idx_saved_for_later_user'),
        ),
        migrations.AddIndex(
            model_name='savedforlater',
            index=models.Index(fields=['stock_item'], name='idx_saved_for_later_stock'),
        ),
        migrations.AddIndex(
            model_name='savedforlater',
            index=models.Index(fields=['saved_at'], name='idx_saved_for_later_saved_at'),
        ),
    ]
