# Generated by Django 5.2.8 on 2025-12-11 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsession',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='business.branch'),
        ),
    ]
