# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Asset Tag')),
                ('name', models.CharField(max_length=200, verbose_name='Asset Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Serial Number')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Purchase Cost')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Value')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salvage Value')),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Depreciation Rate (%)')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance')], default='straight_line', max_length=20, verbose_name='Depreciation Method')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('disposed', 'Disposed'), ('lost', 'Lost/Stolen'), ('damaged', 'Damaged'), ('retired', 'Retired')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=20, null=True, verbose_name='Condition')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Warranty Expiry')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Last Maintenance')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Next Maintenance Due')),
                ('maintenance_schedule', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True, verbose_name='Maintenance Schedule')),
                ('insurance_policy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Policy Number')),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Provider')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='Insurance Expiry')),
                ('insurance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Insurance Value')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Accumulated Depreciation')),
                ('book_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Book Value')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(verbose_name='Audit Date')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='Status')),
                ('location_verified', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location Verified')),
                ('condition_verified', models.CharField(blank=True, max_length=20, null=True, verbose_name='Condition Verified')),
                ('discrepancies', models.TextField(blank=True, null=True, verbose_name='Discrepancies')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recommendations')),
                ('next_audit_date', models.DateField(blank=True, null=True, verbose_name='Next Audit Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Audit',
                'verbose_name_plural': 'Asset Audits',
                'db_table': 'asset_audits',
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Default Depreciation Rate (%)')),
                ('useful_life_years', models.PositiveIntegerField(default=5, verbose_name='Useful Life (Years)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Depreciation Amount')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Accumulated Depreciation')),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Book Value')),
                ('posted_to_finance', models.BooleanField(default=False, verbose_name='Posted to Finance')),
                ('finance_transaction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Finance Transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Depreciation',
                'verbose_name_plural': 'Asset Depreciation',
                'db_table': 'asset_depreciation',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(verbose_name='Disposal Date')),
                ('disposal_method', models.CharField(choices=[('sold', 'Sold'), ('scrapped', 'Scrapped'), ('donated', 'Donated'), ('stolen', 'Stolen/Lost'), ('returned', 'Returned to Supplier'), ('recycled', 'Recycled'), ('destroyed', 'Destroyed')], max_length=20, verbose_name='Disposal Method')),
                ('disposal_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Disposal Value')),
                ('reason', models.TextField(verbose_name='Reason for Disposal')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('disposal_certificate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Disposal Certificate')),
            ],
            options={
                'verbose_name': 'Asset Disposal',
                'verbose_name_plural': 'Asset Disposals',
                'db_table': 'asset_disposals',
                'ordering': ['-disposal_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100, unique=True, verbose_name='Policy Number')),
                ('provider', models.CharField(max_length=100, verbose_name='Insurance Provider')),
                ('policy_type', models.CharField(max_length=50, verbose_name='Policy Type')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Coverage Amount')),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Premium Amount')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('deductible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Deductible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Insurance',
                'verbose_name_plural': 'Asset Insurance',
                'db_table': 'asset_insurance',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('emergency', 'Emergency'), ('predictive', 'Predictive'), ('condition_based', 'Condition Based')], max_length=20, verbose_name='Maintenance Type')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Completed Date')),
                ('performed_by', models.CharField(max_length=100, verbose_name='Performed By')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cost')),
                ('description', models.TextField(verbose_name='Description')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='Findings')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recommendations')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Next Maintenance')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred')], default='scheduled', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority')),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Downtime (Hours)')),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenance',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Reservation',
                'verbose_name_plural': 'Asset Reservations',
                'db_table': 'asset_reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=200, verbose_name='From Location')),
                ('to_location', models.CharField(max_length=200, verbose_name='To Location')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transfer Date')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Transfer Reason')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tracking Number')),
            ],
            options={
                'verbose_name': 'Asset Transfer',
                'verbose_name_plural': 'Asset Transfers',
                'db_table': 'asset_transfers',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
