# Generated by Django 5.2 on 2025-10-06 08:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(verbose_name='Audit Date')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='Status')),
                ('location_verified', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location Verified')),
                ('condition_verified', models.CharField(blank=True, max_length=20, null=True, verbose_name='Condition Verified')),
                ('discrepancies', models.TextField(blank=True, null=True, verbose_name='Discrepancies')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recommendations')),
                ('next_audit_date', models.DateField(blank=True, null=True, verbose_name='Next Audit Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Audit',
                'verbose_name_plural': 'Asset Audits',
                'db_table': 'asset_audits',
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Depreciation Amount')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Accumulated Depreciation')),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Book Value')),
                ('posted_to_finance', models.BooleanField(default=False, verbose_name='Posted to Finance')),
                ('finance_transaction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Finance Transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Depreciation',
                'verbose_name_plural': 'Asset Depreciation',
                'db_table': 'asset_depreciation',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AssetInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100, unique=True, verbose_name='Policy Number')),
                ('provider', models.CharField(max_length=100, verbose_name='Insurance Provider')),
                ('policy_type', models.CharField(max_length=50, verbose_name='Policy Type')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Coverage Amount')),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Premium Amount')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('deductible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Deductible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Insurance',
                'verbose_name_plural': 'Asset Insurance',
                'db_table': 'asset_insurance',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Reservation',
                'verbose_name_plural': 'Asset Reservations',
                'db_table': 'asset_reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['name'], 'verbose_name': 'Asset Category', 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AddField(
            model_name='asset',
            name='accumulated_depreciation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Accumulated Depreciation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode'),
        ),
        migrations.AddField(
            model_name='asset',
            name='book_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Book Value'),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance')], default='straight_line', max_length=20, verbose_name='Depreciation Method'),
        ),
        migrations.AddField(
            model_name='asset',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance Expiry'),
        ),
        migrations.AddField(
            model_name='asset',
            name='insurance_policy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Policy Number'),
        ),
        migrations.AddField(
            model_name='asset',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Provider'),
        ),
        migrations.AddField(
            model_name='asset',
            name='insurance_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Insurance Value'),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_schedule',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True, verbose_name='Maintenance Schedule'),
        ),
        migrations.AddField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salvage Value'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Default Depreciation Rate (%)'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='assets.assetcategory'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='useful_life_years',
            field=models.PositiveIntegerField(default=5, verbose_name='Useful Life (Years)'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='disposal_certificate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disposal Certificate'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='downtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Downtime (Hours)'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Date'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tracking Number'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Asset Tag'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='business.branch'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=20, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Value'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Depreciation Rate (%)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('disposed', 'Disposed'), ('lost', 'Lost/Stolen'), ('damaged', 'Damaged'), ('retired', 'Retired')], db_index=True, default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_disposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='disposal_method',
            field=models.CharField(choices=[('sold', 'Sold'), ('scrapped', 'Scrapped'), ('donated', 'Donated'), ('stolen', 'Stolen/Lost'), ('returned', 'Returned to Supplier'), ('recycled', 'Recycled'), ('destroyed', 'Destroyed')], max_length=20, verbose_name='Disposal Method'),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('emergency', 'Emergency'), ('predictive', 'Predictive'), ('condition_based', 'Condition Based')], max_length=20, verbose_name='Maintenance Type'),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='transfer_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transfer Date'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['custodian'], name='idx_assets_custodian'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='idx_assets_serial'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['barcode'], name='idx_assets_barcode'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['purchase_date'], name='idx_assets_purchase_date'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['warranty_expiry'], name='idx_assets_warranty'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['next_maintenance'], name='idx_assets_next_maint'),
        ),
        migrations.AddField(
            model_name='assetaudit',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetaudit',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetaudit',
            name='custodian_verified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdepreciation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetinsurance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetreservation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetreservation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetreservation',
            name='reserved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assetdepreciation',
            unique_together={('asset', 'period_start')},
        ),
    ]
