# Generated by Django 5.2 on 2025-10-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetaudit_assetdepreciation_assetinsurance_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetmaintenance',
            table=None,
        ),
    ]
