# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import finance.invoicing.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0002_initial'),
        ('core_orders', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_orders.baseorder')),
                ('invoice_number', models.CharField(blank=True, help_text='Auto-generated invoice number', max_length=100, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('payment_terms', models.CharField(choices=[('due_on_receipt', 'Due on Receipt'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('net_90', 'Net 90'), ('custom', 'Custom')], default='due_on_receipt', max_length=20)),
                ('custom_terms_days', models.IntegerField(blank=True, help_text='Custom payment terms in days', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When invoice was sent to customer', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When customer viewed the invoice', null=True)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('scheduled_send_date', models.DateTimeField(blank=True, help_text='Schedule invoice to be sent', null=True)),
                ('template_name', models.CharField(choices=[('standard', 'Standard Template'), ('modern', 'Modern Template'), ('classic', 'Classic Template'), ('professional', 'Professional Template')], default='standard', max_length=50)),
                ('customer_notes', models.TextField(blank=True, default='Thanks for your business.')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('payment_gateway_enabled', models.BooleanField(default=False)),
                ('payment_gateway_name', models.CharField(blank=True, help_text='e.g., Stripe, M-Pesa', max_length=50)),
                ('payment_link', models.URLField(blank=True, help_text='Payment gateway link', max_length=500)),
                ('share_token', models.CharField(blank=True, help_text='Public share token for view-only access', max_length=64, null=True, unique=True)),
                ('share_url', models.URLField(blank=True, help_text='Public share URL', max_length=500)),
                ('is_shared', models.BooleanField(default=False, help_text='Whether this invoice has been shared publicly')),
                ('shared_at', models.DateTimeField(blank=True, help_text='When invoice was first shared', null=True)),
                ('allow_public_payment', models.BooleanField(default=False, help_text='Allow customers to pay via public share link')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_interval', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('next_invoice_date', models.DateField(blank=True, null=True)),
                ('approvals', models.ManyToManyField(blank=True, related_name='invoices', to='approvals.approval')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invoices', to=settings.AUTH_USER_MODEL)),
                ('source_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_invoices', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
            bases=('core_orders.baseorder',),
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_orders.baseorder')),
                ('debit_note_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('debit_note_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(help_text='Reason for issuing debit note')),
                ('source_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Debit Note',
                'verbose_name_plural': 'Debit Notes',
                'ordering': ['-debit_note_date', '-created_at'],
            },
            bases=('core_orders.baseorder',),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_orders.baseorder')),
                ('credit_note_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('credit_note_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(help_text='Reason for issuing credit note')),
                ('source_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
                'ordering': ['-credit_note_date', '-created_at'],
            },
            bases=('core_orders.baseorder',),
        ),
        migrations.CreateModel(
            name='InvoiceEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(choices=[('sent', 'Invoice Sent'), ('reminder', 'Payment Reminder'), ('thank_you', 'Thank You'), ('overdue', 'Overdue Notice')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Email Log',
                'verbose_name_plural': 'Invoice Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(default=finance.invoicing.models.InvoicePayment._today)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Payment',
                'verbose_name_plural': 'Invoice Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
