# Generated by Django 5.2.8 on 2025-12-03 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('invoicing', '0001_initial'),
        ('payment', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='source_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_invoices', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='invoiceemaillog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='invoicing.invoice'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='invoicing.invoice'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='payment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.paymentaccounts'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='idx_invoice_number'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='idx_invoice_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='idx_invoice_due_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['scheduled_send_date'], name='idx_invoice_scheduled'),
        ),
    ]
