# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('invoicing', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='payment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.paymentaccounts'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='idx_invoice_number'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='idx_invoice_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='idx_invoice_due_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['scheduled_send_date'], name='idx_invoice_scheduled'),
        ),
        migrations.AddIndex(
            model_name='debitnote',
            index=models.Index(fields=['debit_note_number'], name='idx_debit_note_number'),
        ),
        migrations.AddIndex(
            model_name='debitnote',
            index=models.Index(fields=['source_invoice'], name='idx_debit_note_invoice'),
        ),
        migrations.AddIndex(
            model_name='debitnote',
            index=models.Index(fields=['debit_note_date'], name='idx_debit_note_date'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['credit_note_number'], name='idx_credit_note_number'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['source_invoice'], name='idx_credit_note_invoice'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['credit_note_date'], name='idx_credit_note_date'),
        ),
    ]
