# Generated by Django 5.2.8 on 2025-12-03 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0002_initial'),
        ('invoicing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_orders.baseorder')),
                ('credit_note_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('credit_note_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(help_text='Reason for issuing credit note')),
                ('source_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
                'ordering': ['-credit_note_date', '-created_at'],
                'indexes': [models.Index(fields=['credit_note_number'], name='idx_credit_note_number'), models.Index(fields=['source_invoice'], name='idx_credit_note_invoice'), models.Index(fields=['credit_note_date'], name='idx_credit_note_date')],
            },
            bases=('core_orders.baseorder',),
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_orders.baseorder')),
                ('debit_note_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('debit_note_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(help_text='Reason for issuing debit note')),
                ('source_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Debit Note',
                'verbose_name_plural': 'Debit Notes',
                'ordering': ['-debit_note_date', '-created_at'],
                'indexes': [models.Index(fields=['debit_note_number'], name='idx_debit_note_number'), models.Index(fields=['source_invoice'], name='idx_debit_note_invoice'), models.Index(fields=['debit_note_date'], name='idx_debit_note_date')],
            },
            bases=('core_orders.baseorder',),
        ),
    ]
