# Generated by Django 5.2.8 on 2025-12-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_creditnote_debitnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='allow_public_payment',
            field=models.BooleanField(default=False, help_text='Allow customers to pay via public share link'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Whether this invoice has been shared publicly'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='share_token',
            field=models.CharField(blank=True, help_text='Public share token for view-only access', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='share_url',
            field=models.URLField(blank=True, help_text='Public share URL', max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shared_at',
            field=models.DateTimeField(blank=True, help_text='When invoice was first shared', null=True),
        ),
    ]
