# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
            options={
                'db_table': 'crm_campaign_performance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(choices=[('banner', 'Banner'), ('email', 'Email'), ('social', 'Social Media'), ('sms', 'SMS'), ('promotional', 'Promotional'), ('seasonal', 'Seasonal'), ('product_launch', 'Product Launch'), ('loyalty', 'Loyalty Program')], default='banner', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Highest'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Lowest')], default=3)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('badge', models.CharField(blank=True, default='New', max_length=200, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_impressions', models.PositiveIntegerField(blank=True, null=True)),
                ('max_clicks', models.PositiveIntegerField(blank=True, null=True)),
                ('landing_page_url', models.URLField(blank=True, null=True)),
                ('cta_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='business.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_campaigns',
                'ordering': ['priority', '-start_date'],
            },
        ),
    ]
