# Generated by Django 5.2.7 on 2025-11-15 11:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('contacts', '0001_initial'),
        ('stockinventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(choices=[('banner', 'Banner'), ('email', 'Email'), ('social', 'Social Media'), ('sms', 'SMS'), ('promotional', 'Promotional'), ('seasonal', 'Seasonal'), ('product_launch', 'Product Launch'), ('loyalty', 'Loyalty Program')], default='banner', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Highest'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Lowest')], default=3)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('badge', models.CharField(blank=True, default='New', max_length=200, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_impressions', models.PositiveIntegerField(blank=True, null=True)),
                ('max_clicks', models.PositiveIntegerField(blank=True, null=True)),
                ('landing_page_url', models.URLField(blank=True, null=True)),
                ('cta_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='business.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('featured_products', models.ManyToManyField(blank=True, related_name='product_campaigns', to='stockinventory.stockinventory')),
                ('seller', models.ForeignKey(blank=True, limit_choices_to={'contact_type': 'Suppliers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_campaigns', to='contacts.contact')),
                ('stock_items', models.ManyToManyField(blank=True, related_name='stock_campaigns', to='stockinventory.stockinventory')),
                ('target_audience', models.ManyToManyField(blank=True, related_name='targeted_campaigns', to='contacts.contact')),
                ('target_branches', models.ManyToManyField(blank=True, related_name='targeted_campaigns', to='business.branch')),
            ],
            options={
                'db_table': 'crm_campaigns',
                'ordering': ['priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'crm_campaign_performance',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='idx_campaign_type'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='idx_campaign_status'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['priority'], name='idx_campaign_priority'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='idx_campaign_active'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date'], name='idx_campaign_start_date'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['end_date'], name='idx_campaign_end_date'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_at'], name='idx_campaign_created_at'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['seller'], name='idx_campaign_seller'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['branch'], name='idx_campaign_branch'),
        ),
        migrations.AddIndex(
            model_name='campaignperformance',
            index=models.Index(fields=['campaign', 'date'], name='idx_campaign_performance_date'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignperformance',
            unique_together={('campaign', 'date')},
        ),
    ]
