# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('contacts', '0001_initial'),
        ('stockinventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='featured_products',
            field=models.ManyToManyField(blank=True, related_name='product_campaigns', to='stockinventory.stockinventory'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='seller',
            field=models.ForeignKey(blank=True, limit_choices_to={'contact_type': 'Suppliers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_campaigns', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='stock_items',
            field=models.ManyToManyField(blank=True, related_name='stock_campaigns', to='stockinventory.stockinventory'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_audience',
            field=models.ManyToManyField(blank=True, related_name='targeted_campaigns', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_branches',
            field=models.ManyToManyField(blank=True, related_name='targeted_campaigns', to='business.branch'),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='campaigns.campaign'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='idx_campaign_type'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='idx_campaign_status'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['priority'], name='idx_campaign_priority'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='idx_campaign_active'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date'], name='idx_campaign_start_date'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['end_date'], name='idx_campaign_end_date'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_at'], name='idx_campaign_created_at'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['seller'], name='idx_campaign_seller'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['branch'], name='idx_campaign_branch'),
        ),
        migrations.AddIndex(
            model_name='campaignperformance',
            index=models.Index(fields=['campaign', 'date'], name='idx_campaign_performance_date'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignperformance',
            unique_together={('campaign', 'date')},
        ),
    ]
