# Generated by Django 5.2.7 on 2025-11-15 11:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_won', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'crm_pipeline_stages',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['name'], name='idx_pipeline_stage_name'), models.Index(fields=['order'], name='idx_pipeline_stage_order'), models.Index(fields=['is_won'], name='idx_pipeline_stage_is_won'), models.Index(fields=['is_lost'], name='idx_pipeline_stage_is_lost')],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='contacts.contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='pipeline.pipelinestage')),
            ],
            options={
                'db_table': 'crm_deals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stage'], name='idx_deal_stage'), models.Index(fields=['contact'], name='idx_deal_contact'), models.Index(fields=['lead'], name='idx_deal_lead'), models.Index(fields=['owner'], name='idx_deal_owner'), models.Index(fields=['close_date'], name='idx_deal_close_date'), models.Index(fields=['created_at'], name='idx_deal_created_at'), models.Index(fields=['updated_at'], name='idx_deal_updated_at')],
            },
        ),
    ]
