# Generated by Django 5.2.8 on 2025-12-03 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('contacts', '0003_alter_contact_added_on'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payment',
            name='approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-approval threshold', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer for money IN', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('in', 'Money In'), ('out', 'Money Out')], default='in', help_text='Money flow direction', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Account from/to which payment flows', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.paymentaccounts'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('invoice_payment', 'Invoice Payment'), ('sales_payment', 'Sales Payment'), ('refund_received', 'Refund Received'), ('expense_payment', 'Expense Payment'), ('purchase_order_payment', 'Purchase Order Payment'), ('payroll_payment', 'Payroll Payment'), ('supplier_payment', 'Supplier Payment'), ('tax_payment', 'Tax Payment'), ('refund_issued', 'Refund Issued'), ('transfer', 'Account Transfer'), ('adjustment', 'Balance Adjustment')], default='invoice_payment', help_text='Type of payment transaction', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier for money OUT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money')], help_text='Mobile money provider used for payment', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank', 'Bank Transfer'), ('cod', 'Cash on Delivery'), ('cheque', 'Cheque')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='idx_payment_type'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['direction'], name='idx_payment_direction'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_account'], name='idx_payment_account'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer'], name='idx_payment_customer'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['supplier'], name='idx_payment_supplier'),
        ),
    ]
