# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pospayment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.sales'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='idx_payment_type'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['direction'], name='idx_payment_direction'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='idx_payment_method'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payment_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_number'], name='idx_payment_reference'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='idx_payment_transaction'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='idx_payment_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_account'], name='idx_payment_account'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer'], name='idx_payment_customer'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['supplier'], name='idx_payment_supplier'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['mobile_money_provider'], name='idx_payment_mobile_provider'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['branch'], name='idx_payment_branch'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['phone_number'], name='idx_payment_phone'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['kra_compliance'], name='idx_payment_kra_compliance'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='idx_payment_created_at'),
        ),
    ]
