# Generated by Django 5.2.8 on 2025-12-11 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('business', '0001_initial'),
        ('contacts', '0006_alter_contact_added_on'),
        ('payment', '0002_alter_payment_options_payment_approval_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payments', to='business.branch'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='business.branch'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['branch'], name='idx_payment_branch'),
        ),
    ]
