# Generated by Django 5.2.7 on 2025-11-15 11:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('snapshot_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('active_customers', models.IntegerField(default=0)),
                ('churned_customers', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('retention_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('customer_lifetime_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('retention_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('first_order_date', models.DateTimeField(blank=True, null=True)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('days_since_last_order', models.IntegerField(default=0)),
                ('order_frequency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('customer_segment', models.CharField(choices=[('new', 'New Customer'), ('active', 'Active Customer'), ('loyal', 'Loyal Customer'), ('at_risk', 'At Risk Customer'), ('churned', 'Churned Customer')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Analytics',
                'verbose_name_plural': 'Customer Analytics',
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(max_length=100)),
                ('segment_description', models.TextField(blank=True)),
                ('min_orders', models.IntegerField(default=0)),
                ('max_orders', models.IntegerField(blank=True, null=True)),
                ('min_total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('max_total_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('min_days_since_last_order', models.IntegerField(default=0)),
                ('max_days_since_last_order', models.IntegerField(blank=True, null=True)),
                ('customer_count', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Segment',
                'verbose_name_plural': 'Customer Segments',
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecast_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('predicted_quantity', models.IntegerField(default=0)),
                ('predicted_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('confidence_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('historical_quantity', models.IntegerField(default=0)),
                ('historical_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('seasonal_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Forecast',
                'verbose_name_plural': 'Sales Forecasts',
            },
        ),
    ]
