# Generated by Django 5.2.7 on 2025-11-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('business', '0001_initial'),
        ('contacts', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssnapshot',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='business.branch'),
        ),
        migrations.AddField(
            model_name='customeranalytics',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_analytics', to='business.branch'),
        ),
        migrations.AddField(
            model_name='customeranalytics',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_segments', to='business.branch'),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_forecasts', to='business.branch'),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.products'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['snapshot_date'], name='idx_analytics_snapshot_date'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['snapshot_type'], name='idx_analytics_snapshot_type'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['branch'], name='idx_analytics_snapshot_branch'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['created_at'], name='idx_analytics_snapshot_created'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticssnapshot',
            unique_together={('branch', 'snapshot_date', 'snapshot_type')},
        ),
        migrations.AddIndex(
            model_name='customeranalytics',
            index=models.Index(fields=['customer_segment'], name='idx_customer_analytics_segment'),
        ),
        migrations.AddIndex(
            model_name='customeranalytics',
            index=models.Index(fields=['total_spent'], name='idx_cust_analytics_spent'),
        ),
        migrations.AddIndex(
            model_name='customeranalytics',
            index=models.Index(fields=['last_order_date'], name='idx_cust_analytics_last_order'),
        ),
        migrations.AddIndex(
            model_name='customeranalytics',
            index=models.Index(fields=['customer'], name='idx_cust_analytics_customer'),
        ),
        migrations.AddIndex(
            model_name='customeranalytics',
            index=models.Index(fields=['branch'], name='idx_cust_analytics_branch'),
        ),
        migrations.AddIndex(
            model_name='customeranalytics',
            index=models.Index(fields=['created_at'], name='idx_cust_analytics_created'),
        ),
        migrations.AlterUniqueTogether(
            name='customeranalytics',
            unique_together={('customer', 'branch')},
        ),
        migrations.AddIndex(
            model_name='customersegment',
            index=models.Index(fields=['branch'], name='idx_customer_segment_branch'),
        ),
        migrations.AddIndex(
            model_name='customersegment',
            index=models.Index(fields=['segment_name'], name='idx_customer_segment_name'),
        ),
        migrations.AddIndex(
            model_name='customersegment',
            index=models.Index(fields=['created_at'], name='idx_cust_segment_created'),
        ),
        migrations.AlterUniqueTogether(
            name='customersegment',
            unique_together={('branch', 'segment_name')},
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['forecast_date'], name='idx_sales_forecast_date'),
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['forecast_period'], name='idx_sales_forecast_period'),
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['product'], name='idx_sales_forecast_product'),
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['branch'], name='idx_sales_forecast_branch'),
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['created_at'], name='idx_sales_forecast_created_at'),
        ),
        migrations.AlterUniqueTogether(
            name='salesforecast',
            unique_together={('branch', 'product', 'forecast_date', 'forecast_period')},
        ),
    ]
