# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='ExpenseEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('sent', 'Expense Report Sent'), ('approval_request', 'Approval Request'), ('approved', 'Approval Notification'), ('rejected', 'Rejection Notification'), ('payment_request', 'Payment Request')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='sent', max_length=20)),
            ],
            options={
                'verbose_name': 'Expense Email Log',
                'verbose_name_plural': 'Expense Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_note', models.TextField(blank=True, null=True)),
                ('paid_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Payments',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
                ('attach_document', models.FileField(blank=True, null=True, upload_to='expense/documents/')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expense_note', models.TextField(blank=True, null=True)),
                ('is_refund', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('interval_type', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50, null=True)),
                ('recurring_interval', models.PositiveIntegerField(default=0)),
                ('repetitions', models.IntegerField(default=0)),
                ('applicable_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_taxes', to='business.taxrates')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='business.branch')),
                ('expense_for_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conatct_expenses', to='contacts.contact')),
                ('expense_for_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
