# Generated by Django 5.2.7 on 2025-11-15 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('business', '0001_initial'),
        ('contacts', '0001_initial'),
        ('payment', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'indexes': [models.Index(fields=['name'], name='idx_expense_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
                ('attach_document', models.FileField(blank=True, null=True, upload_to='expense/documents/')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expense_note', models.TextField(blank=True, null=True)),
                ('is_refund', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('interval_type', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50, null=True)),
                ('recurring_interval', models.PositiveIntegerField(default=0)),
                ('repetitions', models.IntegerField(default=0)),
                ('applicable_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_taxes', to='business.taxrates')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='business.branch')),
                ('expense_for_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conatct_expenses', to='contacts.contact')),
                ('expense_for_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pos.register')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_expenses', to='expenses.expensecategory')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_note', models.TextField(blank=True, null=True)),
                ('paid_on', models.DateField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to='expenses.expense')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to='payment.payment')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_payment_accounts', to='accounts.paymentaccounts')),
            ],
            options={
                'verbose_name_plural': 'Expense Payments',
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['register'], name='idx_expense_register'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch'], name='idx_expense_branch'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='idx_expense_category'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['reference_no'], name='idx_expense_reference_no'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date_added'], name='idx_expense_date_added'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_for_user'], name='idx_expense_for_user'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_for_contact'], name='idx_expense_for_contact'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['applicable_tax'], name='idx_expense_tax'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_refund'], name='idx_expense_is_refund'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_recurring'], name='idx_expense_is_recurring'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['expense'], name='idx_expense_payment_expense'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['payment'], name='idx_expense_payment_payment'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['paid_on'], name='idx_expense_payment_paid_on'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['payment_account'], name='idx_expense_payment_account'),
        ),
    ]
