# Generated by Django 5.2.8 on 2025-12-03 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('sent', 'Expense Report Sent'), ('approval_request', 'Approval Request'), ('approved', 'Approval Notification'), ('rejected', 'Rejection Notification'), ('payment_request', 'Payment Request')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='expenses.expense')),
            ],
            options={
                'verbose_name': 'Expense Email Log',
                'verbose_name_plural': 'Expense Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
