# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('expenses', '0001_initial'),
        ('payment', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pos.register'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['name'], name='idx_expense_category_name'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_expenses', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='expenseemaillog',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='expensepayment',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='expensepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='expensepayment',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_payment_accounts', to='accounts.paymentaccounts'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['register'], name='idx_expense_register'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch'], name='idx_expense_branch'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='idx_expense_category'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['reference_no'], name='idx_expense_reference_no'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date_added'], name='idx_expense_date_added'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_for_user'], name='idx_expense_for_user'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_for_contact'], name='idx_expense_for_contact'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['applicable_tax'], name='idx_expense_tax'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_refund'], name='idx_expense_is_refund'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_recurring'], name='idx_expense_is_recurring'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['expense'], name='idx_expense_payment_expense'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['payment'], name='idx_expense_payment_payment'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['paid_on'], name='idx_expense_payment_paid_on'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['payment_account'], name='idx_expense_payment_account'),
        ),
    ]
