# Generated by Django 5.2.7 on 2025-11-15 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appraisals', '0001_initial'),
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_appraisals', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='appraisalcycle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appraisal_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisalcycle',
            name='locations',
            field=models.ManyToManyField(related_name='appraisal_cycles', to='core.regions'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='appraisals.appraisalcycle'),
        ),
        migrations.AddField(
            model_name='appraisalresponse',
            name='appraisal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='appraisals.appraisal'),
        ),
        migrations.AddField(
            model_name='appraisalresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisals.appraisalquestion'),
        ),
        migrations.AddField(
            model_name='appraisaltemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisalquestion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='appraisals.appraisaltemplate'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisals.appraisaltemplate'),
        ),
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='goalprogress',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='appraisals.goal'),
        ),
        migrations.AddField(
            model_name='goalprogress',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
