# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Planned Quantity')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Actual Quantity')),
                ('cost', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Cost')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Batch Raw Material',
                'verbose_name_plural': 'Batch Raw Materials',
            },
        ),
        migrations.CreateModel(
            name='FormulaIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Formula Ingredient',
                'verbose_name_plural': 'Formula Ingredients',
            },
        ),
        migrations.CreateModel(
            name='ManufacturingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('total_batches', models.IntegerField(default=0, verbose_name='Total Batches')),
                ('completed_batches', models.IntegerField(default=0, verbose_name='Completed Batches')),
                ('failed_batches', models.IntegerField(default=0, verbose_name='Failed Batches')),
                ('total_production_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Total Production Quantity')),
                ('total_raw_material_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Total Raw Material Cost')),
                ('total_labor_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Total Labor Cost')),
                ('total_overhead_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Total Overhead Cost')),
            ],
            options={
                'verbose_name': 'Manufacturing Analytics',
                'verbose_name_plural': 'Manufacturing Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Formula Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('expected_output_quantity', models.DecimalField(decimal_places=4, help_text='The expected quantity of final product produced by this formula', max_digits=14, verbose_name='Expected Output Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Product Formula',
                'verbose_name_plural': 'Product Formulas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='Batch Number')),
                ('scheduled_date', models.DateTimeField(verbose_name='Scheduled Date')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='planned', max_length=20, verbose_name='Status')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Planned Quantity')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Actual Quantity')),
                ('labor_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Labor Cost')),
                ('overhead_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Overhead Cost')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Production Batch',
                'verbose_name_plural': 'Production Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Check Date')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=10, verbose_name='Result')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Quality Check',
                'verbose_name_plural': 'Quality Checks',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('transaction_type', models.CharField(choices=[('production', 'Production'), ('testing', 'Testing'), ('wastage', 'Wastage'), ('return', 'Return'), ('adjustment', 'Adjustment')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Raw Material Usage',
                'verbose_name_plural': 'Raw Material Usages',
            },
        ),
    ]
