# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('product', '0001_initial'),
        ('stockinventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrawmaterial',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_usages', to='stockinventory.stockinventory'),
        ),
        migrations.AddField(
            model_name='batchrawmaterial',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_materials', to='stockinventory.unit'),
        ),
        migrations.AddField(
            model_name='formulaingredient',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_usages', to='stockinventory.stockinventory'),
        ),
        migrations.AddField(
            model_name='formulaingredient',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_ingredients', to='stockinventory.unit'),
        ),
        migrations.AddIndex(
            model_name='manufacturinganalytics',
            index=models.Index(fields=['date'], name='idx_manuf_analytics_date'),
        ),
        migrations.AddField(
            model_name='productformula',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_formulas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productformula',
            name='final_product',
            field=models.ForeignKey(help_text='The final product that this formula produces', on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='product.products'),
        ),
        migrations.AddField(
            model_name='productformula',
            name='output_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_formulas', to='stockinventory.unit'),
        ),
        migrations.AddField(
            model_name='formulaingredient',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='manufacturing.productformula'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='business.branch'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='manufacturing.productformula'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchrawmaterial',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='manufacturing.productionbatch'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='manufacturing.productionbatch'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterialusage',
            name='finished_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_usages', to='product.products'),
        ),
        migrations.AddField(
            model_name='rawmaterialusage',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_products', to='stockinventory.stockinventory'),
        ),
        migrations.AddIndex(
            model_name='productformula',
            index=models.Index(fields=['name'], name='idx_product_formula_name'),
        ),
        migrations.AddIndex(
            model_name='productformula',
            index=models.Index(fields=['final_product'], name='idx_product_formula_final_prod'),
        ),
        migrations.AddIndex(
            model_name='productformula',
            index=models.Index(fields=['is_active'], name='idx_product_formula_is_active'),
        ),
        migrations.AddIndex(
            model_name='productformula',
            index=models.Index(fields=['created_by'], name='idx_product_formula_created_by'),
        ),
        migrations.AddIndex(
            model_name='productformula',
            index=models.Index(fields=['created_at'], name='idx_product_formula_created_at'),
        ),
        migrations.AddIndex(
            model_name='productformula',
            index=models.Index(fields=['updated_at'], name='idx_product_formula_updated_at'),
        ),
        migrations.AddIndex(
            model_name='productformula',
            index=models.Index(fields=['version'], name='idx_product_formula_version'),
        ),
        migrations.AlterUniqueTogether(
            name='productformula',
            unique_together={('name', 'version')},
        ),
        migrations.AddIndex(
            model_name='formulaingredient',
            index=models.Index(fields=['formula'], name='idx_formula_ingredient_formula'),
        ),
        migrations.AddIndex(
            model_name='formulaingredient',
            index=models.Index(fields=['raw_material'], name='idx_formula_ingredient_raw_mat'),
        ),
        migrations.AddIndex(
            model_name='formulaingredient',
            index=models.Index(fields=['unit'], name='idx_formula_ingredient_unit'),
        ),
        migrations.AlterUniqueTogether(
            name='formulaingredient',
            unique_together={('formula', 'raw_material')},
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['batch_number'], name='idx_prod_batch_number'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['formula'], name='idx_production_batch_formula'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['branch'], name='idx_production_batch_branch'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['scheduled_date'], name='idx_prod_batch_scheduled'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['start_date'], name='idx_prod_batch_start'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['end_date'], name='idx_prod_batch_end'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['status'], name='idx_prod_batch_status'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['created_by'], name='idx_prod_batch_created_by'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['supervisor'], name='idx_prod_batch_supervisor'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['created_at'], name='idx_prod_batch_created'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['updated_at'], name='idx_prod_batch_updated'),
        ),
        migrations.AddIndex(
            model_name='batchrawmaterial',
            index=models.Index(fields=['batch'], name='idx_batch_raw_material_batch'),
        ),
        migrations.AddIndex(
            model_name='batchrawmaterial',
            index=models.Index(fields=['raw_material'], name='idx_batch_raw_mat_raw_mat'),
        ),
        migrations.AddIndex(
            model_name='batchrawmaterial',
            index=models.Index(fields=['unit'], name='idx_batch_raw_material_unit'),
        ),
        migrations.AlterUniqueTogether(
            name='batchrawmaterial',
            unique_together={('batch', 'raw_material')},
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['batch'], name='idx_quality_check_batch'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['check_date'], name='idx_quality_check_check_date'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['inspector'], name='idx_quality_check_inspector'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['result'], name='idx_quality_check_result'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['created_at'], name='idx_quality_check_created_at'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialusage',
            index=models.Index(fields=['finished_product'], name='idx_raw_mat_usage_finished'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialusage',
            index=models.Index(fields=['raw_material'], name='idx_raw_mat_usage_raw_mat'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialusage',
            index=models.Index(fields=['transaction_type'], name='idx_raw_mat_usage_txn_type'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialusage',
            index=models.Index(fields=['transaction_date'], name='idx_raw_mat_usage_txn_date'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialusage',
            index=models.Index(fields=['created_at'], name='idx_raw_mat_usage_created'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialusage',
            unique_together={('finished_product', 'raw_material', 'transaction_date')},
        ),
    ]
