# Generated by Django 5.2.7 on 2025-11-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='categories/display/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active')),
                ('level', models.PositiveIntegerField(default=0, help_text='Category hierarchy level (0=root, 1=main, 2=sub)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within same level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['level', 'order', 'name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeliveryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the delivery policy', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the delivery policy', null=True)),
                ('min_days', models.PositiveSmallIntegerField(default=1, help_text='Minimum number of days for delivery')),
                ('max_days', models.PositiveSmallIntegerField(default=3, help_text='Maximum number of days for delivery')),
                ('delivery_speed', models.CharField(choices=[('express', 'Express (Same Day)'), ('next_day', 'Next Day'), ('standard', 'Standard (2-4 days)'), ('economy', 'Economy (5-7 days)'), ('international', 'International (7-14 days)')], default='standard', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Set as the default policy')),
                ('is_active', models.BooleanField(default=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Base delivery fee', max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=0.0, help_text='Order amount above which delivery is free (0 means no free delivery)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_policies', to='business.bussiness')),
            ],
            options={
                'verbose_name': 'Delivery Policy',
                'verbose_name_plural': 'Delivery Policies',
                'db_table': 'delivery_policies',
            },
        ),
        migrations.CreateModel(
            name='ProductBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'managed': True,
                'indexes': [models.Index(fields=['title'], name='idx_product_brands_title')],
            },
        ),
        migrations.CreateModel(
            name='ProductModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Models',
                'db_table': 'models',
                'managed': True,
                'indexes': [models.Index(fields=['title'], name='idx_product_models_title')],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hp x2 1033', max_length=500)),
                ('serial', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('dimentions', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_manufactured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.productbrands')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.productmodels')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/%Y%m%d/')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='product.products')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'db_table': 'productimages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductDeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_handling_required', models.BooleanField(default=False, help_text='Requires special handling')),
                ('min_days_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_days_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delivery_fee_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_jumia_express', models.BooleanField(default=False, help_text='Delivered same day or next day')),
                ('is_jumia_prime', models.BooleanField(default=False, help_text='Available for free delivery with prime subscription')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=6, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Length in centimeters', max_digits=6, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Width in centimeters', max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_policies', to='product.deliverypolicy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='product.products')),
            ],
            options={
                'verbose_name': 'Product Delivery Information',
                'verbose_name_plural': 'Product Delivery Information',
                'db_table': 'product_delivery_info',
            },
        ),
        migrations.CreateModel(
            name='RegionalDeliveryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days', models.PositiveSmallIntegerField(blank=True, help_text='Region-specific min days (overrides policy default)', null=True)),
                ('max_days', models.PositiveSmallIntegerField(blank=True, help_text='Region-specific max days (overrides policy default)', null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Region-specific delivery fee (overrides policy default)', max_digits=10, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_policies', to='product.deliverypolicy')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_policies', to='addresses.deliveryregion')),
            ],
            options={
                'verbose_name': 'Regional Delivery Policy',
                'verbose_name_plural': 'Regional Delivery Policies',
                'db_table': 'regional_delivery_policies',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='idx_category_name'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='idx_category_parent'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['status'], name='idx_category_status'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level'], name='idx_category_level'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order'], name='idx_category_order'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='idx_category_created_at'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['title'], name='idx_product_title'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['serial'], name='idx_product_serial'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['sku'], name='idx_product_sku'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['status'], name='idx_product_status'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['is_featured'], name='idx_product_featured'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category'], name='idx_product_category'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['brand'], name='idx_product_brand'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['created_at'], name='idx_product_created_at'),
        ),
        migrations.AddIndex(
            model_name='productimages',
            index=models.Index(fields=['product'], name='idx_product_images_product'),
        ),
        migrations.AlterUniqueTogether(
            name='regionaldeliverypolicy',
            unique_together={('policy', 'region')},
        ),
    ]
