# Generated by Django 5.2.8 on 2025-12-11 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.bussiness'),
        ),
        migrations.AddField(
            model_name='products',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], default='goods', max_length=20),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['business'], name='idx_product_business'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['product_type'], name='idx_product_type'),
        ),
    ]
