apiVersion: v1
kind: Secret
metadata:
  name: erp-api-env
  namespace: erp
type: Opaque
stringData:
  # ============================================
  # DATABASE CONFIGURATION (In-Cluster)
  # ============================================
  # NOTE: These will be dynamically updated during deployment
  # DATABASE_URL will be set by build.sh based on actual database setup
  DATABASE_URL: "postgresql://postgres:__DYNAMIC_PASSWORD__@postgresql.erp.svc.cluster.local:5432/bengo_erp"
  DB_HOST: "postgresql.erp.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "bengo_erp"
  DB_USER: "postgres"
  DB_PASSWORD: "__DYNAMIC_DB_PASSWORD__"

  # ============================================
  # REDIS CONFIGURATION (In-Cluster)
  # ============================================
  # NOTE: These will be dynamically updated during deployment
  REDIS_URL: "redis://:__DYNAMIC_REDIS_PASSWORD__@redis-master.erp.svc.cluster.local:6379/0"
  REDIS_HOST: "redis-master.erp.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "__DYNAMIC_REDIS_PASSWORD__"
  CELERY_BROKER_URL: "redis://:__DYNAMIC_REDIS_PASSWORD__@redis-master.erp.svc.cluster.local:6379/0"
  CELERY_RESULT_BACKEND: "redis://:__DYNAMIC_REDIS_PASSWORD__@redis-master.erp.svc.cluster.local:6379/1"

  # ============================================
  # DJANGO CONFIGURATION
  # ============================================
  DJANGO_SECRET_KEY: "__DYNAMIC_DJANGO_SECRET__"
  DJANGO_SETTINGS_MODULE: "ProcureProKEAPI.settings"
  DEBUG: "False"
  DJANGO_ENV: "production"
  ALLOWED_HOSTS: "erpapi.masterspace.co.ke,localhost,127.0.0.1,*.masterspace.co.ke"

  # ============================================
  # SECURITY & JWT
  # ============================================
  # NOTE: JWT_SECRET will be dynamically generated during deployment
  JWT_SECRET: "__DYNAMIC_JWT_SECRET__"
  SECRET_KEY: "__DYNAMIC_SECRET_KEY__"

  # ============================================
  # CORS & FRONTEND
  # ============================================
  CORS_ALLOWED_ORIGINS: "https://erp.masterspace.co.ke,http://localhost:3000,*.masterspace.co.ke"
  FRONTEND_URL: "https://erp.masterspace.co.ke"

  # ============================================
  # EMAIL CONFIGURATION (Optional)
  # ============================================
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_HOST_USER: "info@codevertexitsolutions.com"
  EMAIL_HOST_PASSWORD: "CHANGE_ME_GMAIL_APP_PASSWORD"
  DEFAULT_FROM_EMAIL: "info@codevertexitsolutions.com"
