# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_orders.baseorder')),
                ('quotation_number', models.CharField(blank=True, help_text='Auto-generated quotation number', max_length=100, unique=True)),
                ('quotation_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(help_text='Quotation expiry date')),
                ('validity_period', models.CharField(choices=[('7_days', '7 Days'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('60_days', '60 Days'), ('90_days', '90 Days'), ('custom', 'Custom')], default='30_days', max_length=20)),
                ('custom_validity_days', models.IntegerField(blank=True, help_text='Custom validity in days', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When quotation was sent to customer', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When customer viewed the quotation', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True, help_text='Introduction text for the quotation')),
                ('customer_notes', models.TextField(blank=True, default='Thank you for considering our services.')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, help_text='Unique token for public share link', max_length=255, null=True, unique=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Whether this quotation has been shared publicly')),
                ('shared_at', models.DateTimeField(blank=True, help_text='When the quotation was first shared', null=True)),
                ('allow_public_payment', models.BooleanField(default=False, help_text='Allow customer to make payment via public link')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-quotation_date', '-created_at'],
            },
            bases=('core_orders.baseorder',),
        ),
        migrations.CreateModel(
            name='QuotationEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(choices=[('sent', 'Quotation Sent'), ('reminder', 'Follow-up Reminder'), ('thank_you', 'Thank You'), ('expired_notice', 'Expiry Notice')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Email Log',
                'verbose_name_plural': 'Quotation Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_number'], name='idx_quotation_number'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_date'], name='idx_quotation_date'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['valid_until'], name='idx_quotation_valid_until'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['is_converted'], name='idx_quotation_converted'),
        ),
    ]
