# Generated by Django 5.2.8 on 2025-12-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='rfq_number',
            field=models.CharField(blank=True, help_text='RFQ (Request for Quotation) reference number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tender_quotation_ref',
            field=models.CharField(blank=True, help_text='Tender/Quotation reference number', max_length=100, null=True),
        ),
    ]
