# Generated by Django 5.2.8 on 2025-12-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='allow_public_payment',
            field=models.BooleanField(default=False, help_text='Allow customer to make payment via public link'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Whether this quotation has been shared publicly'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='share_token',
            field=models.CharField(blank=True, help_text='Unique token for public share link', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shared_at',
            field=models.DateTimeField(blank=True, help_text='When the quotation was first shared', null=True),
        ),
    ]
