# Generated by Django 5.2 on 2025-09-11 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_orders', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='payment.payment'),
        ),
        migrations.AddIndex(
            model_name='baseorder',
            index=models.Index(fields=['order_number'], name='idx_order_number'),
        ),
        migrations.AddIndex(
            model_name='baseorder',
            index=models.Index(fields=['order_type'], name='idx_order_type'),
        ),
        migrations.AddIndex(
            model_name='baseorder',
            index=models.Index(fields=['status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='baseorder',
            index=models.Index(fields=['payment_status'], name='idx_order_payment_status'),
        ),
        migrations.AddIndex(
            model_name='baseorder',
            index=models.Index(fields=['customer'], name='idx_order_customer'),
        ),
        migrations.AddIndex(
            model_name='baseorder',
            index=models.Index(fields=['supplier'], name='idx_order_supplier'),
        ),
        migrations.AddIndex(
            model_name='baseorder',
            index=models.Index(fields=['order_date'], name='idx_order_date'),
        ),
        migrations.AddIndex(
            model_name='baseorder',
            index=models.Index(fields=['source'], name='idx_order_source'),
        ),
        migrations.AddIndex(
            model_name='baseorder',
            index=models.Index(fields=['delivery_type'], name='idx_order_delivery_type'),
        ),
        migrations.AddIndex(
            model_name='baseorder',
            index=models.Index(fields=['kra_compliance'], name='idx_order_kra_compliance'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='idx_order_item_order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_order_item_content'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['sku'], name='idx_order_item_sku'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['order'], name='idx_order_payment_order'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['payment'], name='idx_order_payment_payment'),
        ),
        migrations.AlterUniqueTogether(
            name='orderpayment',
            unique_together={('order', 'payment')},
        ),
    ]
