# Generated by Django 5.2 on 2025-09-11 07:49

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dicount_calculation', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'verbose_name_plural': 'Customer Groups',
                'db_table': 'customer_groups',
                'managed': True,
                'indexes': [models.Index(fields=['group_name'], name='idx_customer_group_name'), models.Index(fields=['dicount_calculation'], name='idx_customer_group_discount')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=100)),
                ('contact_type', models.CharField(choices=[('Suppliers', 'Suppliers'), ('Customers', 'Customers'), ('Customers & Suppliers', 'Customers & Suppliers')], default='Customers', max_length=100)),
                ('designation', models.CharField(help_text='Mr/Mrs/Ms', max_length=100)),
                ('account_type', models.CharField(choices=[('Individual', 'Individual'), ('Business', 'Business')], default='Individual', max_length=100)),
                ('tax_number', models.CharField(blank=True, help_text='Tax Number if a business', max_length=100, null=True)),
                ('business_name', models.CharField(blank=True, help_text='Business Name if a business', max_length=100, null=True)),
                ('business_address', models.CharField(blank=True, help_text='Business Address if a business', max_length=100, null=True)),
                ('alternative_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True)),
                ('added_on', models.DateField(default=datetime.datetime(2025, 9, 11, 7, 49, 1, 695467, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch where this contact is managed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.branch')),
                ('business', models.ForeignKey(help_text='Business this contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='business.bussiness')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('customer_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customergroup')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContactAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('advance_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_sale_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_sale_return_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='contacts.contact')),
            ],
            options={
                'verbose_name_plural': 'Account',
                'db_table': 'contact_accounts',
                'managed': True,
                'indexes': [models.Index(fields=['contact'], name='idx_contact_account_contact')],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_id'], name='idx_contact_id'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_type'], name='idx_contact_type'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user'], name='idx_contact_user'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['business'], name='idx_contact_business'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['branch'], name='idx_contact_branch'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['customer_group'], name='idx_contact_customer_group'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account_type'], name='idx_contact_account_type'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='idx_contact_phone'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_deleted'], name='idx_contact_deleted'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['added_on'], name='idx_contact_added_on'),
        ),
    ]
