# Generated by Django 5.2 on 2025-09-11 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2025, 9, 11, 11, 50, 49, 112662, tzinfo=datetime.timezone.utc)),
        ),
    ]
