# Generated by Django 5.2.7 on 2025-11-16 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2025, 11, 16, 10, 10, 12, 557756, tzinfo=datetime.timezone.utc)),
        ),
    ]
