# Generated by Django 5.2.8 on 2025-12-16 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='landline',
            field=models.CharField(blank=True, help_text='Landline phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2025, 12, 16, 15, 8, 4, 308949, tzinfo=datetime.timezone.utc)),
        ),
    ]
