# Generated by Django 5.2.8 on 2025-12-03 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2025, 12, 3, 15, 47, 37, 867563, tzinfo=datetime.timezone.utc)),
        ),
    ]
