# Generated by Django 5.2.8 on 2025-12-16 15:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('contacts', '0002_add_landline_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2025, 12, 16, 15, 15, 5, 681342, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business this contact belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='business.bussiness'),
        ),
    ]
