# Generated by Django 5.2 on 2025-09-11 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2025, 9, 11, 11, 58, 19, 879985, tzinfo=datetime.timezone.utc)),
        ),
    ]
