# Generated by Django 5.2.8 on 2025-12-16 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_make_biz_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
