# Generated by Django 5.2.7 on 2025-10-16 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2025, 10, 16, 8, 5, 5, 894137, tzinfo=datetime.timezone.utc)),
        ),
    ]
