# Generated by Django 5.2.8 on 2025-12-11 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2025, 12, 11, 22, 6, 9, 473078, tzinfo=datetime.timezone.utc)),
        ),
    ]
