# Generated by Django 5.2.8 on 2025-12-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='director_first_name',
            field=models.CharField(blank=True, help_text='First name of managing director or founder for business accounts', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='director_last_name',
            field=models.CharField(blank=True, help_text='Last name of managing director or founder for business accounts', max_length=100, null=True),
        ),
    ]
