# Generated by Django 5.2.8 on 2025-12-24 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_director_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
