# Generated by Django 5.2.8 on 2025-12-15 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2025, 12, 15, 20, 51, 13, 172856, tzinfo=datetime.timezone.utc)),
        ),
    ]
