# Generated by Django 5.2.8 on 2025-12-15 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_contact_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2025, 12, 15, 21, 2, 36, 598320, tzinfo=datetime.timezone.utc)),
        ),
    ]
