# Generated by Django 5.2 on 2025-09-11 07:49

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('biometric_id', models.CharField(blank=True, help_text='Biometric device/user ID for attendance capture', max_length=100, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude at check-in/out', max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude at check-in/out', max_digits=9, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half-day', 'Half Day')], default='present', max_length=20)),
                ('total_seconds_worked', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hrm_attendance_records',
                'ordering': ['-date', 'employee_id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the attendance rule', max_length=100)),
                ('rule_type', models.CharField(choices=[('late_policy', 'Late Arrival Policy'), ('overtime_policy', 'Overtime Policy'), ('absenteeism_policy', 'Absenteeism Policy'), ('work_hours_policy', 'Work Hours Policy'), ('break_policy', 'Break Time Policy'), ('holiday_policy', 'Holiday Policy')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the rule', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Priority order for rule application (higher = more important)')),
                ('late_threshold_minutes', models.PositiveIntegerField(default=15, help_text='Minutes after shift start time to consider as late')),
                ('late_penalty_type', models.CharField(choices=[('warning', 'Warning'), ('deduction', 'Salary Deduction'), ('disciplinary', 'Disciplinary Action'), ('none', 'No Penalty')], default='warning', max_length=20)),
                ('late_penalty_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty value (amount or percentage)', max_digits=5)),
                ('overtime_threshold_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Hours after which overtime applies', max_digits=4)),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Overtime pay rate multiplier', max_digits=3)),
                ('max_overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Maximum overtime hours per day', max_digits=4)),
                ('consecutive_absent_threshold', models.PositiveIntegerField(default=3, help_text='Consecutive absent days to trigger action')),
                ('monthly_absent_threshold', models.PositiveIntegerField(default=5, help_text='Monthly absent days to trigger action')),
                ('absenteeism_action', models.CharField(choices=[('warning', 'Warning'), ('suspension', 'Suspension'), ('termination', 'Termination Review'), ('none', 'No Action')], default='warning', max_length=20)),
                ('standard_work_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Standard work hours per day', max_digits=4)),
                ('min_work_hours', models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='Minimum work hours to count as full day', max_digits=4)),
                ('max_work_hours', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Maximum work hours per day', max_digits=4)),
                ('break_duration_minutes', models.PositiveIntegerField(default=60, help_text='Total break time in minutes per day')),
                ('break_intervals', models.JSONField(default=list, help_text='Break intervals in minutes (e.g., [30, 30] for two 30-min breaks)')),
                ('public_holidays', models.JSONField(default=list, help_text='List of public holidays (dates)')),
                ('holiday_pay_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Holiday work pay multiplier', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hrm_attendance_rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hrm_off_days',
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hrm_work_shifts',
                'ordering': ['id'],
            },
        ),
    ]
