# Generated by Django 5.2.7 on 2025-11-15 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('business', '0001_initial'),
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this rule applies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='business.branch'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='business.bussiness'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='core.departments'),
        ),
        migrations.AddField(
            model_name='esssettings',
            name='exempt_roles',
            field=models.ManyToManyField(blank=True, help_text='User groups/roles that are exempt from shift-based login restrictions', to='auth.group', verbose_name='Exempt Roles/Groups'),
        ),
        migrations.AddField(
            model_name='offday',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_days', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_entries', to='core.projects'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='attendance.timesheet'),
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['name'], name='idx_work_shift_name'),
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['created_at'], name='idx_work_shift_created_at'),
        ),
        migrations.AddField(
            model_name='shiftrotation',
            name='current_active_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_rotations', to='attendance.workshift'),
        ),
        migrations.AddField(
            model_name='shiftrotation',
            name='last_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_rotations', to='attendance.workshift'),
        ),
        migrations.AddField(
            model_name='shiftrotation',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='rotations', to='attendance.workshift'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workshift'),
        ),
        migrations.AddField(
            model_name='workshiftschedule',
            name='work_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='attendance.workshift'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['rule_type'], name='idx_attendance_rule_type'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['is_active'], name='idx_attendance_rule_active'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['priority'], name='idx_attendance_rule_priority'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['business'], name='idx_attendance_rule_business'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['branch'], name='idx_attendance_rule_branch'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['department'], name='idx_attendance_rule_department'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['created_at'], name='idx_attendance_rule_created_at'),
        ),
        migrations.AddIndex(
            model_name='esssettings',
            index=models.Index(fields=['enable_shift_based_restrictions'], name='idx_ess_shift_restrict'),
        ),
        migrations.AddIndex(
            model_name='esssettings',
            index=models.Index(fields=['created_at'], name='idx_ess_created_at'),
        ),
        migrations.AddIndex(
            model_name='offday',
            index=models.Index(fields=['employee', 'date'], name='idx_offday_emp_date'),
        ),
        migrations.AddIndex(
            model_name='offday',
            index=models.Index(fields=['employee'], name='idx_offday_employee'),
        ),
        migrations.AddIndex(
            model_name='offday',
            index=models.Index(fields=['date'], name='idx_offday_date'),
        ),
        migrations.AddIndex(
            model_name='offday',
            index=models.Index(fields=['created_at'], name='idx_offday_created_at'),
        ),
        migrations.AlterUniqueTogether(
            name='offday',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('employee', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='timesheetentry',
            unique_together={('timesheet', 'date')},
        ),
        migrations.AddIndex(
            model_name='shiftrotation',
            index=models.Index(fields=['title'], name='idx_shift_rotation_title'),
        ),
        migrations.AddIndex(
            model_name='shiftrotation',
            index=models.Index(fields=['is_active'], name='idx_shift_rotation_active'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='idx_att_emp_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='idx_att_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee'], name='idx_attendance_employee'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['work_shift'], name='idx_attendance_work_shift'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['check_in'], name='idx_attendance_check_in'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['check_out'], name='idx_attendance_check_out'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['biometric_id'], name='idx_attendance_biometric'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='idx_attendance_status'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['created_at'], name='idx_attendance_created_at'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='workshiftschedule',
            index=models.Index(fields=['work_shift', 'day'], name='idx_shift_schedule_shift_day'),
        ),
        migrations.AddIndex(
            model_name='workshiftschedule',
            index=models.Index(fields=['day'], name='idx_shift_schedule_day'),
        ),
        migrations.AddIndex(
            model_name='workshiftschedule',
            index=models.Index(fields=['is_working_day'], name='idx_shift_schedule_working'),
        ),
        migrations.AlterUniqueTogether(
            name='workshiftschedule',
            unique_together={('work_shift', 'day')},
        ),
    ]
