# Generated by Django 5.2 on 2025-09-11 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('business', '0001_initial'),
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this rule applies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='business.branch'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='business.bussiness'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='core.departments'),
        ),
        migrations.AddField(
            model_name='offday',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_days', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['name'], name='idx_work_shift_name'),
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['start_time'], name='idx_work_shift_start_time'),
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['end_time'], name='idx_work_shift_end_time'),
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['created_at'], name='idx_work_shift_created_at'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workshift'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['rule_type'], name='idx_attendance_rule_type'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['is_active'], name='idx_attendance_rule_active'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['priority'], name='idx_attendance_rule_priority'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['business'], name='idx_attendance_rule_business'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['branch'], name='idx_attendance_rule_branch'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['department'], name='idx_attendance_rule_department'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['created_at'], name='idx_attendance_rule_created_at'),
        ),
        migrations.AddIndex(
            model_name='offday',
            index=models.Index(fields=['employee', 'date'], name='idx_offday_emp_date'),
        ),
        migrations.AddIndex(
            model_name='offday',
            index=models.Index(fields=['employee'], name='idx_offday_employee'),
        ),
        migrations.AddIndex(
            model_name='offday',
            index=models.Index(fields=['date'], name='idx_offday_date'),
        ),
        migrations.AddIndex(
            model_name='offday',
            index=models.Index(fields=['created_at'], name='idx_offday_created_at'),
        ),
        migrations.AlterUniqueTogether(
            name='offday',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='idx_att_emp_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='idx_att_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee'], name='idx_attendance_employee'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['work_shift'], name='idx_attendance_work_shift'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['check_in'], name='idx_attendance_check_in'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['check_out'], name='idx_attendance_check_out'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['biometric_id'], name='idx_attendance_biometric'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='idx_attendance_status'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['created_at'], name='idx_attendance_created_at'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'date')},
        ),
    ]
