# Generated by Django 5.2 on 2025-09-11 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0002_initial'),
        ('core_orders', '0001_initial'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_orders.baseorder')),
                ('approved_budget', models.DecimalField(decimal_places=2, help_text='Approved budget for this purchase', max_digits=15)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost after receiving', max_digits=15, null=True)),
                ('delivery_instructions', models.TextField(blank=True, help_text='Delivery instructions')),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('approvals', models.ManyToManyField(blank=True, related_name='purchase_orders', to='approvals.approval')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='requisitions.procurementrequest')),
            ],
            bases=('core_orders.baseorder',),
        ),
    ]
