# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('orders', '0001_initial'),
        ('payment', '0002_initial'),
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='requisitions.procurementrequest'),
        ),
        migrations.AddField(
            model_name='purchaseorderpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_payments', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='purchaseorderpayment',
            name='payment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.paymentaccounts'),
        ),
        migrations.AddField(
            model_name='purchaseorderpayment',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_payments', to='orders.purchaseorder'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderpayment',
            index=models.Index(fields=['purchase_order'], name='idx_po_payment_po'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderpayment',
            index=models.Index(fields=['payment'], name='idx_po_payment_payment'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderpayment',
            index=models.Index(fields=['payment_date'], name='idx_po_payment_date'),
        ),
    ]
