# Generated by Django 5.2.8 on 2025-12-03 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('orders', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_payments', to='payment.payment')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.paymentaccounts')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_payments', to='orders.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Payment',
                'verbose_name_plural': 'Purchase Order Payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['purchase_order'], name='idx_po_payment_po'), models.Index(fields=['payment'], name='idx_po_payment_payment'), models.Index(fields=['payment_date'], name='idx_po_payment_date')],
            },
        ),
    ]
