# Generated by Django 5.2.8 on 2025-12-16 10:21

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Reward',
                'verbose_name_plural': 'Customer Rewards',
            },
        ),
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name_plural': 'Sale Return Items',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('sale_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('additional_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('balance_overdue', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2025, 12, 16, 10, 21, 3, 88331, tzinfo=datetime.timezone.utc))),
                ('date_updated', models.DateTimeField(default=datetime.datetime(2025, 12, 16, 10, 21, 3, 88345, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Quotation', 'Quotation'), ('Final', 'Final')], default='Final', max_length=20, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Due', 'Due'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', max_length=20, null=True)),
                ('paymethod', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('Card', 'Card'), ('Bank', 'Bank'), ('Advance', 'Advance'), ('Other', 'Other')], default='Cash', max_length=20, null=True)),
                ('sale_source', models.CharField(choices=[('pos', 'POS'), ('online', 'Online'), ('other', 'Other')], default='pos', max_length=50)),
                ('delete_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='salesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Sales Items',
                'verbose_name_plural': 'Sales Items',
                'db_table': 'salesitems',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Sales Logs',
                'ordering': ['-log_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date_returned', models.DateTimeField(auto_now_add=True)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('return_amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Due', 'Due'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sale Returns',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_note', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('deliverd', 'Delivered'), ('cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('delivered_to', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping',
                'db_table': 'shipping',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShippingDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='shipping/files')),
            ],
            options={
                'verbose_name_plural': 'Shipping Documents',
                'db_table': 'shipping_documents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SuspendedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('items', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=255)),
                ('clientId', models.CharField(max_length=255)),
                ('transactionType', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], default='withdrawal', max_length=20)),
                ('transactionRef', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Mpesa Transactions',
                'verbose_name_plural': 'Mpesa Transactions',
                'db_table': 'mpesa_transactions',
                'managed': True,
                'indexes': [models.Index(fields=['clientId'], name='idx_mpesa_transaction_client'), models.Index(fields=['transactionType'], name='idx_mpesa_transaction_type'), models.Index(fields=['transactionRef'], name='idx_mpesa_transaction_ref'), models.Index(fields=['date'], name='idx_mpesa_transaction_date')],
            },
        ),
        migrations.CreateModel(
            name='PayTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=1)),
                ('period', models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Sale Pay Terms',
                'db_table': 'sale_pay_terms',
                'ordering': ['duration'],
                'managed': True,
                'indexes': [models.Index(fields=['duration'], name='idx_pay_term_duration'), models.Index(fields=['period'], name='idx_pay_term_period')],
            },
        ),
        migrations.CreateModel(
            name='POSAdvanceSaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('advance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_sales', to='payroll.advances')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Advance Sale Record',
                'verbose_name_plural': 'POS Advance Sale Records',
                'db_table': 'pos_advance_sale_records',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('cash_at_opening', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cash_at_closing', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='business.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_registers', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_registers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cash Register',
            },
        ),
    ]
