# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_initial'),
        ('business', '0001_initial'),
        ('contacts', '0001_initial'),
        ('pos', '0001_initial'),
        ('stockinventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returneditem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='stockinventory.stockinventory'),
        ),
        migrations.AddField(
            model_name='sales',
            name='attendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='sales',
            name='pay_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.payterm'),
        ),
        migrations.AddField(
            model_name='sales',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pos.register'),
        ),
        migrations.AddField(
            model_name='posadvancesalerecord',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_advance_record', to='pos.sales'),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='pos.sales'),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesitems', to='pos.sales'),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesitems', to='stockinventory.stockinventory', verbose_name='sale item'),
        ),
        migrations.AddField(
            model_name='saleslogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='attendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='original_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='pos.sales'),
        ),
        migrations.AddField(
            model_name='returneditem',
            name='return_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='pos.salesreturn'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='delivered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipping',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='pos.sales'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='addresses.addressbook'),
        ),
        migrations.AddField(
            model_name='saleslogs',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_tasks', to='pos.shipping'),
        ),
        migrations.AddField(
            model_name='shippingdocuments',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_documents', to='pos.shipping'),
        ),
        migrations.AddField(
            model_name='suspendedsale',
            name='attendant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspendedsale',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.branch'),
        ),
        migrations.AddField(
            model_name='suspendedsale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['branch'], name='idx_register_branch'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['user'], name='idx_register_user'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['is_open'], name='idx_register_is_open'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['opened_at'], name='idx_register_opened_at'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['closed_at'], name='idx_register_closed_at'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['opened_by'], name='idx_register_opened_by'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['closed_by'], name='idx_register_closed_by'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['register'], name='idx_sales_register'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['customer'], name='idx_sales_customer'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['attendant'], name='idx_sales_attendant'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['sale_id'], name='idx_sales_sale_id'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['status'], name='idx_sales_status'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['payment_status'], name='idx_sales_payment_status'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['paymethod'], name='idx_sales_paymethod'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['sale_source'], name='idx_sales_source'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['date_added'], name='idx_sales_date_added'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['delete_status'], name='idx_sales_delete_status'),
        ),
        migrations.AddIndex(
            model_name='posadvancesalerecord',
            index=models.Index(fields=['sale'], name='idx_pos_advance_sale'),
        ),
        migrations.AddIndex(
            model_name='posadvancesalerecord',
            index=models.Index(fields=['advance'], name='idx_pos_advance_advance'),
        ),
        migrations.AddIndex(
            model_name='posadvancesalerecord',
            index=models.Index(fields=['reference_id'], name='idx_pos_advance_ref'),
        ),
        migrations.AddIndex(
            model_name='posadvancesalerecord',
            index=models.Index(fields=['date_created'], name='idx_pos_advance_date'),
        ),
        migrations.AddIndex(
            model_name='posadvancesalerecord',
            index=models.Index(fields=['created_by'], name='idx_pos_advance_created_by'),
        ),
        migrations.AddIndex(
            model_name='customerreward',
            index=models.Index(fields=['sale'], name='idx_customer_reward_sale'),
        ),
        migrations.AddIndex(
            model_name='customerreward',
            index=models.Index(fields=['date_created'], name='idx_customer_reward_created'),
        ),
        migrations.AddIndex(
            model_name='salesitems',
            index=models.Index(fields=['sale'], name='idx_sales_items_sale'),
        ),
        migrations.AddIndex(
            model_name='salesitems',
            index=models.Index(fields=['stock_item'], name='idx_sales_items_stock'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['return_id'], name='idx_sales_return_id'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['original_sale'], name='idx_sales_return_original_sale'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['attendant'], name='idx_sales_return_attendant'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['date_returned'], name='idx_sales_return_date'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['payment_status'], name='idx_sales_return_pay_status'),
        ),
        migrations.AddIndex(
            model_name='returneditem',
            index=models.Index(fields=['return_record'], name='idx_returned_item_record'),
        ),
        migrations.AddIndex(
            model_name='returneditem',
            index=models.Index(fields=['stock_item'], name='idx_returned_item_stock'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['sale'], name='idx_shipping_sale'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['shipping_address'], name='idx_shipping_address'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['status'], name='idx_shipping_status'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['delivered_by'], name='idx_shipping_delivered_by'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['created_at'], name='idx_shipping_created_at'),
        ),
        migrations.AddIndex(
            model_name='saleslogs',
            index=models.Index(fields=['shipping'], name='idx_sales_logs_shipping'),
        ),
        migrations.AddIndex(
            model_name='saleslogs',
            index=models.Index(fields=['log_date'], name='idx_sales_logs_log_date'),
        ),
        migrations.AddIndex(
            model_name='saleslogs',
            index=models.Index(fields=['user'], name='idx_sales_logs_user'),
        ),
        migrations.AddIndex(
            model_name='shippingdocuments',
            index=models.Index(fields=['shipping'], name='idx_shipping_docs_shipping'),
        ),
    ]
