# Generated by Django 5.2.7 on 2025-10-25 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 21, 47, 35, 57102, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 21, 47, 35, 57116, tzinfo=datetime.timezone.utc)),
        ),
    ]
