# Generated by Django 5.2 on 2025-09-11 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_sales_date_added_alter_sales_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 11, 58, 19, 940841, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 11, 58, 19, 940855, tzinfo=datetime.timezone.utc)),
        ),
    ]
