# Generated by Django 5.2.7 on 2025-10-25 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_sales_date_added_alter_sales_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 23, 32, 11, 183160, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 23, 32, 11, 183176, tzinfo=datetime.timezone.utc)),
        ),
    ]
