# Generated by Django 5.2.8 on 2025-12-11 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_sales_date_added_alter_sales_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 11, 22, 21, 56, 250385, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 11, 22, 21, 56, 250402, tzinfo=datetime.timezone.utc)),
        ),
    ]
