# Generated by Django 5.2.7 on 2025-10-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delegated', 'Delegated'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, help_text='Internal comments', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('delegated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_approved', models.BooleanField(default=False, help_text='Whether this was auto-approved')),
                ('approval_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount being approved', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approvals',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('title', models.CharField(help_text='Title of the approval request', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount being requested', max_digits=15, null=True)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Order of this step in the workflow')),
                ('name', models.CharField(help_text='Name of this approval step', max_length=255)),
                ('approver_type', models.CharField(choices=[('user', 'Specific User'), ('role', 'Role'), ('department_head', 'Department Head'), ('manager', 'Manager'), ('owner', 'Business Owner')], default='user', max_length=50)),
                ('approver_role', models.CharField(blank=True, help_text='Role required for approval', max_length=100, null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this step is required')),
                ('can_delegate', models.BooleanField(default=False, help_text='Whether approver can delegate to someone else')),
                ('auto_approve', models.BooleanField(default=False, help_text='Whether this step auto-approves')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_steps',
                'ordering': ['workflow', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the approval workflow', max_length=255)),
                ('workflow_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('expense', 'Expense'), ('invoice', 'Invoice'), ('leave_request', 'Leave Request'), ('overtime', 'Overtime'), ('payroll', 'Payroll'), ('contract', 'Contract'), ('requisition', 'Requisition'), ('general', 'General')], help_text='Type of workflow', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('requires_multiple_approvals', models.BooleanField(default=False, help_text='Whether multiple approvals are required')),
                ('approval_order_matters', models.BooleanField(default=True, help_text='Whether approval order is important')),
                ('auto_approve_on_threshold', models.BooleanField(default=False, help_text='Auto approve if amount is below threshold')),
                ('approval_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Amount threshold for auto approval', max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_workflows',
                'ordering': ['name'],
            },
        ),
    ]
