# Generated by Django 5.2.8 on 2025-12-16 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approval',
            name='delegated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approver_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to='core.departments'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_requests', to='approvals.approvalstep'),
        ),
        migrations.AddField(
            model_name='approval',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='approvals.approvalstep'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['workflow_type'], name='idx_approval_workflow_type'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['is_active'], name='idx_approval_workflow_active'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='approvals.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approval',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='approvals.approvalworkflow'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['workflow'], name='idx_approval_step_workflow'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['step_number'], name='idx_approval_step_number'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['approver_type'], name='idx_approval_step_app_type'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('workflow', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_approval_request_content'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['workflow'], name='idx_approval_request_workflow'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requester'], name='idx_approval_request_requester'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status'], name='idx_approval_request_status'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['urgency'], name='idx_approval_request_urgency'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['submitted_at'], name='idx_approval_request_submitted'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_approval_content'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['workflow'], name='idx_approval_workflow'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['step'], name='idx_approval_step'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver'], name='idx_approval_approver'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['status'], name='idx_approval_status'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['requested_at'], name='idx_approval_submitted_at'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approved_at'], name='idx_approval_approved_at'),
        ),
    ]
