# Generated by Django 5.2.8 on 2025-12-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationAnalytics',
        ),
        migrations.DeleteModel(
            name='NotificationTest',
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='from_email',
            field=models.EmailField(default='gadmin@masterserpace.co.ke', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='from_name',
            field=models.CharField(default='Masters ERP', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='smtp_host',
            field=models.CharField(default='smtppro.zoho.com', max_length=100),
        ),
    ]
