# Generated by Django 5.2.7 on 2025-11-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('core_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorderlink',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_links', to='core_orders.baseorder'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['supplier'], name='idx_contract_supplier'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['title'], name='idx_contract_title'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date'], name='idx_proc_contract_start'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['end_date'], name='idx_proc_contract_end'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='idx_proc_contract_status'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_at'], name='idx_contract_created_at'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['supplier', 'status'], name='idx_contract_supplier_status'),
        ),
        migrations.AddIndex(
            model_name='contractorderlink',
            index=models.Index(fields=['contract'], name='idx_proc_colink_contract'),
        ),
        migrations.AddIndex(
            model_name='contractorderlink',
            index=models.Index(fields=['purchase_order'], name='idx_proc_colink_po'),
        ),
        migrations.AlterUniqueTogether(
            name='contractorderlink',
            unique_together={('contract', 'purchase_order')},
        ),
    ]
